### ISSUE TITLE
Who uses curlies?!

### ISSUE THREAD

**Issue by dkseschneider** [chargeover/chargeover_php#14]
We attempted to upgrade a project to PHP 8, at received the following error in ChargeOverAPI/Object.php:

`Array and string offset syntax with curly braces is no longer supported`

(I wasn't even aware curly braces was an option, to be honest.)

Making this compatible with PHP 8 may be as simple as changing the offset references from curly braces to square brackets.

**Comment by dkseschneider** [comment]
@keith-chargeover Thanks for making this change! However, you committed some API credentials in that commit. Just a heads up.

**Comment by consolibyte** [comment]
They are example credentials and don't actually point to anything real, but thanks for the heads-up, we'll remove them!

**Comment by dkseschneider** [comment]
> 
> 
> They are example credentials and don't actually point to anything real, but thanks for the heads-up, we'll remove them!

Sounds good. I couldn't tell from the outside. Thanks again for the change!

**Comment by highstrike** [comment]
Can we have a new tag release with these fixes? because installing the package through composer gives us version 1.4 which is from 2019 and doesn't work with php 8 because of the curly brackets

Thanks!

**Comment by highstrike** [comment]
@keith-chargeover FYI

**Comment by dkseschneider** [comment]
> @keith-chargeover FYI

@highstrike If you don't get a response here, I'd recommend reaching out to ChargeOver support directly. They've always been very responsive.

**Comment by highstrike** [comment]
@dkseschneider I know, thanks, I'll send this to my manager to get in touch them
currently I'm using `dev-master` for local development, but when the project launches I'd rather have a version there :)
